language: go
go:
  - 1.8
  - 1.9
  - tip

install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip -d /tmp
  - sudo cp /tmp/bin/protoc /usr/bin/protoc
  - sudo chmod 777 /usr/bin/protoc
  - rm protoc-3.1.0-linux-x86_64.zip
  # After 1.9 hits stable, replace this link
  # It is only used for gofmt
  - wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
  - tar -C /tmp -xvf go1.9.linux-amd64.tar.gz go/bin/gofmt
  - sudo mv /tmp/go/bin/gofmt /usr/bin/gofmt
  - rm go1.9.linux-amd64.tar.gz

before_script:
  - go get -u github.com/ChimeraCoder/gojson/gojson
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/gogo/protobuf/protoc-gen-gofast
  - pushd $GOPATH/src/github.com/gogo/protobuf/
  - git checkout v0.5
  - popd
  - go install github.com/gogo/protobuf/protoc-gen-gofast
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/stringer

  # This is needed to fix https://github.com/golang/go/issues/21387
  - if [ "$TRAVIS_GO_VERSION" = "1.8" ]; then go install; fi


  - go generate
  # We need to ignore changes to this one file
  # because the go-generated version will have a different
  # fileDescriptor0 depending on which version of Go was used
  # to build protoc-gen-go.
  - git checkout ssf/sample.pb.go
  - dep ensure -v

  # We need to use gofmt built with 1.9+
  # on *all* builds
  # because some vendored files use type alias syntax
  - /usr/bin/gofmt -w .

  # See the corresponding lines in the Dockerfile for an explanation
  # of this logic
  - git add .
  - git diff --cached
  - git diff-index --cached --exit-code HEAD

script:
  - if [ "$TRAVIS_GO_VERSION" = "1.8" ]; then go list ./... | grep -v vendor | xargs go test -race -v -timeout 60s; fi
  - if [ "$TRAVIS_GO_VERSION" != "1.8" ]; then echo $TRAVIS_GO_VERSION; go test -race -v -timeout 60s ./...; fi
